{% set name = "xorg-libXtst" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.x.org/releases/individual/lib/{{ name.split('-')[1] }}-{{ version }}.tar.gz
  sha256: 244ba6e1c5ffa44f1ba251affdfa984d55d99c94bb925a342657e5e7aaf6d39c

build:
  number: 3
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - make
    - autoconf
    - automake
    - gettext
    - libtool
  host:
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-libx11 {{ xorg_libx11 }}
    - xorg-libxext {{ xorg_libxext }}
    - xorg-libxi {{ xorg_libxi }}
    - xorg-util-macros ==1.20.2

test:
  commands:
    - test -f $PREFIX/lib/libXtst.dylib  # [osx]
    - test -f $PREFIX/lib/libXtst.so     # [linux]

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxtst
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxtst
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org X11 test-event library.
  description: The X.org X11 test-event library.

extra:
  recipe-maintainers:
    - pkgw
    - ehfd
