# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "wxGV8StluntDtV/Av50jjoXHAtzbY+MqYSlWKBp9eFTJePsAA5YvA3J2iwtcjpetjaz646CAj+bOLEszB2uGAKrXMyoj7n3PuGrkiLg/BnNHiNmL+wag9nurTv52LZRdD15pUPJLRUArkD2jK3Kgl0Y6GP0QmTldNBD6pScoMNivXHa7D4laykjy4eZ2Dk9YcPHRMc5a6dUJgb/gNjirXEpgPLSbFjTG9zBEyZZ/gKwjrE5MPe6zTDAnpv1FzABq+4tgRHvelWcD16Ow4XFofVToh9AZPI675nX2BSfSMSW04dAw4jFTkFD8lFzlwQoAMZ1HrL9pr/4nkKRQD3tWc4uSK69fkWiUUbL90e4HHI4nyzFwzwV2uUw+zVE63oOloiob+4COXoxPzeXa9TseDQb961MvsyGVD5jbzVjOxV+4hzfwn9uy5cmx0ZQjME1p7KsjzzLuQdoT4qUBBQJlMKqxZIj7p+9GMpt0Kv5lCO13uUozeNPYoee10FgsJkfJEItEE8YheY/cvePpA9iZz++xFQg4xnwYuBWVeiwAUpQm8MjngKX5quC86adPxZeIUD96lx6uiqOSBr3gmhpkpkEawikbuy9h1Ga5MmZM98GkfI6l5PfztIF4cQDhE+JdM54RCFrxjeMRMg3IV3KMdk06pLqDMyEbn3OnTEYpanc="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
