travis:
  secure:
    BINSTAR_TOKEN: e96RAHU/V75xKfZs7U26e+bV3+uOUESaoO6rA9n0YCu9F2UASR9q9Zj9c1ICk0L48Wt1d7gXoO1flcL+Np3+uLNHVZQELnvDNPH7JwcPYTklzFZamUu5Y/UyXkmtArs9NBe0oiDBmwKrEnJRiOe6B94ghul0d2359jZqBQv/qNlg4i+Viv9CRs/NB/duVDhFS6alLFKWUJxLhjRRHXTxR6x52zvWgqA8d0GlV/Nhweck1yP7U82MucsUe06KX1iIFPG0IQWUuS+pEyUAJ8VjBooT8iIva2sgPRpznTYGbSxG/9HfbnM4/TTKERUigSbkLA9yLy0aNpSM0iEo+f+YsBT6o6bUDaC6ffjygewE1+W7G7BVvLxLkR7cha3aXsdhTuPWLAqj1I0joDoX7CaHEnde/ris9V3uIlZMNMTpX8moMeP3YdvfroeroUR++WRhX/opkstieOqpNKIORmEjGiTIRYeH7HYMS6tTWY6C8aXUm539jGygAn0Tw6Run/o7eL05KwiZjVb8IeL6ufwYnTOkBsINhoVAETPgyO0VdEJsahLfyTMsEHeC//Qso4K/KOtEWZQwaEhZoJvS/fd6TJKG+5OrDqI/rCEix9/ORdw9mrJ/ORzV5YXnzYWtYqCKX+68+Nx6DuUrqP3sf75GxJZbYy1dpjqUaQptB4+eDZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
